version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_container
    restart: unless-stopped
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./my-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=express-db
    networks:
      - express_api_network

  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - db
    networks:
      - express_api_network

  redis:
    image: redis
    container_name: redis_container
    restart: unless-stopped
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379
    expose:
      - 6379

  redis_insight:
    image: redislabs/redisinsight
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001

volumes:
  my-db:
  redis_volume:


networks:
  express_api_network: